### ISSUE TITLE
bike-rack

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#102]
Particularly relevant for mobile projects, see [this issue.](https://github.com/nationalparkservice/places-mobile/issues/26)

**Comment by jakecoolidge** [comment]
Tom P. initially came up with this bike rack symbol:

![bike-rack-tomp](https://cloud.githubusercontent.com/assets/11392872/13504107/3d9a66a0-e130-11e5-9ceb-4de63e22bbe2.png)

Lauren with the sign dept. felt that a bicycle of some kind needed to be integrated to make it more explicitly "bike rack". Note Tom's bike repair symbol:

![bike-repair-tomp](https://cloud.githubusercontent.com/assets/11392872/13504112/496e0482-e130-11e5-8ff9-af76fd8a08b3.png)

My bike rack variation incorporates the bike element from the bike repair symbol and pairs it with a simple u-shaped rack:

![bike-rack-jakec](https://cloud.githubusercontent.com/assets/11392872/13504120/51e573a2-e130-11e5-97e0-0533deaa67fd.png)

<img src="https://cloud.githubusercontent.com/assets/11392872/13504213/bfc46252-e130-11e5-97a5-62e9ceee2626.png" alt="bike-rack-32" width="32" height="32"/>
(actual size for 32px symbol)

**Comment by chadlawlis** [comment]
:+1:

**Comment by jakecoolidge** [comment]
I sent email to Tom and Lauren with a link to this thread so they can see it/weigh in on it as well.
