### ISSUE TITLE
Symbolize campgrounds vs. campsites

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#12]
In updating Park Tiles with a new POI overlay, we realized we were using the "Campground" symbol for both large campgrounds, like Cades Cove (which can accommodate up to 120 campers), and backcountry campsites that accommodate perhaps three tents, at the most. [See Park Tiles issue no.148](https://github.com/nationalparkservice/park-tiles/issues/148#issuecomment-103580501)

@jimmyrocks has updated our rendering to provide us with both campgrounds and campsites as FCategories in our Mapbox sources. Now we need to find a way to visually differentiate between these categories. In my initial web search, I couldn't find much in terms of precedents. In the attached image, I propose using our existing single "tent" icon (small version) for backcountry campsites, and one of at least three larger, more complex symbols for campgrounds that graphically indicate multiple sites within a campground. Three initial concepts are found along the central axis of the image. From left to right, we have a "cluster" of four tents, a "row" of three tents, and a large tent with four squares. Let me know what think of these options and the more general prospect of supporting these categories.

![campground-alternatives](https://cloud.githubusercontent.com/assets/11392872/7730007/1cc87658-fed5-11e4-9e21-61209bdacb6a.png)

**Comment by jimmyrocks** [comment]
I like the multiple tents on top of each other that best #MyTwoCents

**Comment by nateirwin** [comment]
Agreed. It looks like the "peak" of the third tent should be moved up a few pixels though?

**Comment by jakecoolidge** [comment]
You guys are referring to the middle icon, what I'm calling the "row" alternative? That was my initial idea. Side note, I'm going to talk to Tom Patterson later today, so I hope to learn more about how HFC has thought about this.

**Comment by nateirwin** [comment]
Yep, that's the one. Have you run this by @makella?

**Comment by jakecoolidge** [comment]
She's looked at it, yes. She's glad I'll be talking to Tom about it.

**Comment by makella** [comment]
My suggestion is to talk to Tom Patterson first which it looks like Jake will be doing later on today.

**Comment by makella** [comment]
What I've seen done in the past is differentiating by color (same is done for backcountry ranger stations) I can't see to find an example though but I'm sure Tom will know which maps to look at.

**Comment by jakecoolidge** [comment]
Some notes on this matter from my conversation yesterday with Tom: 
- I didn't get a lot of traction on my more complex symbols, and in the end I think less is more.
- As an alternative, Tom suggested using size as the visual variable to differentiate between campgrounds and campsites. I tested this yesterday, but I think it wasn't working because I already vary size according to zoom level, so it created confusion. 
- Tom also noted that, in the past, one of the most straight-forward way the NPS has dealt with this distinction visually is to use a single tent symbol for backcountry sites, and a tent symbol enclosed in a box for larger campgrounds. My current thinking runs along these lines, though I'm trying to implement it in a less pixel-intensive way.

Have a look at [this map](http://www.nps.gov/maps/full.html?mapId=49250cc7-8e62-4fc3-ace5-33acceb885ac) and zoom in on GRSM. In a park like GRCA, some of the backcountry sites are tagged as campgrounds, but it will now be easy to identify them. This is the same map linked in the open Park Tiles issue.
