### ISSUE TITLE
Convert all HFC symbols

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#126]
See HFC's new symbol roster, released April 20, 2016, [here.](https://www.nps.gov/hfc/carto/map-symbols.cfm)

**Comment by jeffschuler** [comment]
It was my expectation, upon finding this repo, that it would include all of the icons shown in the PDF/Illustrator symbols files on the <a href="https://www.nps.gov/hfc/carto/map-symbols.cfm">Map Symbols & Patterns for NPS Maps</a> page. I see that that's not the case.

It looks to me like this is the appropriate issue aiming to make that so...? (I see that issue #23 looks to be asking for the same thing.)

What needs to happen to make this so? It looks like each of the icons in this set are individually tailored for each available size. Can I assume that that necessary manual labor is what is holding up the other icons from being added?

Could we possibly add all of the missing symbols to this repo in a single icon, non-ideal state for folks like me to try to make use of in the meantime while the various different sizes and colorings are built?

Is there someplace for me to get the missing symbols besides extracting them manually from the Illustrator file?

Thanks much!

**Comment by jakecoolidge** [comment]
completed; will be added to library with v2.5.0
