### ISSUE TITLE
Aquatic Invasive Species Decontamination Station

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/symbol-library#130]
Renamed from "Zebra Mussel Decontamination Station" (see https://github.com/nationalparkservice/places-data/issues/624 for context, #75 for zebra-mussel-decontamination symbol).

@jakecoolidge has been in touch with Tom P from HFC about this https://github.com/nationalparkservice/places-data/issues/624#issuecomment-195499571 and will generate the new symbol when possible.

**Comment by jakecoolidge** [comment]
looks like we forgot to close this; symbol is already part of the library
