### ISSUE TITLE
Standardize and unify symbol library into single repository

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#15]
Up to this point, we have handled the map symbols we use in Park Tiles and Builder separately. Worse, it can be difficult to track down current versions of symbol artwork, as some only reside, in draft form, on my local drive. This is due in part to the fact that the current NPMaki repo is forked from Maki and designed specifically to produce sprites and pngs that are compatible in Builder. A standardized library will facilitate better use of this resource.

**Comment by nateirwin** [comment]
Look forward to working on this!

**Comment by jakecoolidge** [comment]
Done--we now have all symbols used in Park Tiles alongside a separate directory for the tools used to create Builder symbols.

**Comment by nateirwin** [comment]
Does this mean we can delete this repository?

https://github.com/nationalparkservice/symbol-library/

**Comment by jakecoolidge** [comment]
Yes, I'll do that now.
