### ISSUE TITLE
Create food box icon

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#20]
Shared, bear-safe food storage at campgrounds. See [this issue.](https://github.com/nationalparkservice/places-data/issues/65)

**Comment by tpcolson** [comment]
Bump.

**Comment by jakecoolidge** [comment]
Also known as a food cache. We'll be supporting it in Places with a  type rendered out as "Food Box / Food Cache"; underlying tags "storage":"food"
