### ISSUE TITLE
Add symbol for spring feature

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/symbol-library#22]
This might be outside the scope of this repository, but some I&M networks monitor springs, and I've also seen them symbolized on some unigrid maps I have.

[See here](http://www.nps.gov/hfc/carto/symbols/map_symbols.pdf) how NPS HFC symbolizes spring features (look under Misc. Symbols).  It does not explain the difference between the `circle` vs. the `circle with short irregular line` nor the `hollow circle` vs. `filled circle`.  My guess would be non-flowing vs. flowing and perennial vs. year-round, respectively.  But perhaps we could get HFC to comment on this topic?

Some quick research shows that there does not seem to be a standard for hydrologic features.  [USGS Topos](http://pubs.usgs.gov/gip/TopographicMapSymbols/topomapsymbols.pdf) and [National Map](http://nationalmap.gov/ustopo/images/US_Topo_Map_Symbols.pdf) use the `circles` for wells.  All three sources use the `circle with short irregular line` to symbolize springs, but NPS seems to use `circle` and `circle with short irregular line` interchangeably.

Interestingly there was a [standard put forth by USGS back in 1906!](http://makingmaps.net/2008/03/06/map-symbols-wells-and-springs/)

**Comment by jakecoolidge** [comment]
I really appreciate how you've researched and compiled some reference sources to help us think about handling this symbol. I'll also reach out to HFC to see if they could provide some clarification on how they've used spring symbols in the past.

**Comment by ryanjhodge** [comment]
No problem, having fun researching it - just found the [full USGS 1906 reference](http://pubs.usgs.gov/wsp/0160/report.pdf), pg 18 puts forth the standard, and indeed suggests `circle` to be used for wells and `circle with short irregular line` for springs.

**Comment by tpcolson** [comment]
Bump

**Comment by ryanjhodge** [comment]
:+1: Sorry - accidentally clicked "Close and Post"

**Comment by jakecoolidge** [comment]
Many weeks later, and I'm proposing a rather radical departure from the traditional USGS symbol, which initially looked like this when modified to fit in our symbol library:

<img src="https://cloud.githubusercontent.com/assets/11392872/9913453/253ad4be-5c6a-11e5-880f-00a58eaf81e1.png" width="82" height="54" alt="spring-v1" >

Now I'm proposing something that
- doesn't use color
- hopefully better fits with the other symbols in the library
- is a little "heftier" with its pixels&mdash;I find the linework in the first version starts to break down at the smaller sizes

<img src="https://cloud.githubusercontent.com/assets/11392872/9913783/d11fe6a6-5c6b-11e5-9763-2e848e665bee.png" width="110" height="54" alt="spring-v2" >

I'm going to mull this over, and welcome your feedback in the meantime!

**Comment by nateirwin** [comment]
I like the new icons.

**Comment by ryanjhodge** [comment]
After seeing all the symbols together in the MailChimp email this morning, I definitely agree the new icon is a better fit into the "look and feel" of the other icons.  Nice Job!

**Comment by jakecoolidge** [comment]
Thanks, @ryanjhodge!
