### ISSUE TITLE
new icon request; searching for icons

### ISSUE THREAD

**Issue by Coritawaters** [nationalparkservice/symbol-library#220]
Hi, 
We are looking for an icon that might represent cultural traditional use on rivers-- I'm thinking an icon of a bivalve, like an oyster or scallop. Do these exist? 

We are also searching for an icon for rafting -- and have a suggestion with an image of an oar frame raft. Could I share that with someone at HFC?

**Comment by jakecoolidge** [comment]
Hi @Coritawaters, I recently emailed you regarding this issue. Will close this for the time being while we coordinate with the HFC cartographers.
