### ISSUE TITLE
Icon Request: Lock (for boats)

### ISSUE THREAD

**Issue by rangernathan** [nationalparkservice/symbol-library#223]
C&O Canal NHP has a great many locks for moving boats up and down the canal. These are useful landmarks for park visitors. It would be nice to be able to indicate them on a map. I didn't see an existing icon for locks in the library.

**Comment by jakecoolidge** [comment]
I've added a lock symbol. With the release of NPMap.js 4.2, the symbol will be available in NPMap Builder. In the meantime, the symbol is available in the source directories; see https://github.com/nationalparkservice/symbol-library/blob/gh-pages/src/standalone/lock-black-14.svg, https://github.com/nationalparkservice/symbol-library/blob/gh-pages/src/standalone/lock-black-22.svg.
