### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by spilth** [nationalparkservice/symbol-library#224]
Are the SVGs themselves distributed under the BSD license or just the shell/test scripts provided in the repo?

I'm asking because I've created [my own transformations of the NPS SVGs](https://national-park-symbols.spilth.org) and saw that https://www.nps.gov/carto/app/#!/maps/symbols says that "NPS symbols are free and in the public domain."

**Comment by jakecoolidge** [comment]
Hi @spilth, that's correct, NPS symbol artwork is the public domain, including symbols in this library.

**Comment by spilth** [comment]
Thanks for the reply, @jakecoolidge!
