### ISSUE TITLE
All HFC Icons as Symbols in this library and builder

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/symbol-library#23]
Instead of submitting a unique GH issue for each symbol, it would handy if ALL of the Map Symbols (http://www.nps.gov/hfc/carto/symbols/map_symbols.zip) and Other Symbols (http://www.nps.gov/hfc/carto/symbols/other_symbols.zip) were included in the npmap-symbol-library and included in Builder in the NPMaki option. 

Web manager are extremely reluctant, and in some cases, simply won't embed map content in the CMS that is NOT using official HFC symbols.

**Comment by jakecoolidge** [comment]
completed; will be added to library with v2.5.0
