### ISSUE TITLE
Statue (generic)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#27]
Originally part of [this issue](https://github.com/nationalparkservice/npmap-symbol-library/issues/9)

**Comment by jakecoolidge** [comment]
A couple variations on an early concept for a statue symbol:

![statue-1-32-72](https://cloud.githubusercontent.com/assets/11392872/9532362/7c2ea144-4cc8-11e5-9bf5-a61ecd5bdeb9.png)
![statue-2-32-72](https://cloud.githubusercontent.com/assets/11392872/9532363/7c331fee-4cc8-11e5-8994-b4277e156e55.png)

You may note that I'm only displaying all the 32px size at this time; I'm tweaking my process a bit. Moving forward, I want to make sure the overall concept for the symbol is working, and then I'll take on the next challenge of adapting the symbol to the smaller sizes.

These should be retina-friendly versions of the above artwork:

<img src="https://cloud.githubusercontent.com/assets/11392872/9532364/7c366aa0-4cc8-11e5-8390-aa1f130c3057.png" width="32px" height="32px" alt="statue variation 1"/>

<img src="https://cloud.githubusercontent.com/assets/11392872/9532365/7c371dce-4cc8-11e5-802c-53f326ad0ab3.png" width="32px" height="32px" alt="statue variation 2"/>

**Comment by nateirwin** [comment]
I like the first one better. The second one looks too "Statue of Liberty"-esque to me.

**Comment by jimmyrocks** [comment]
Have you thought about 🗽 or 🗿?

**Comment by jakecoolidge** [comment]
I've started calling the second one the "hitchhiker" statue. So it seems like the first might be better. @jimmyrocks: no. ;)

**Comment by chadlawlis** [comment]
+1 to https://github.com/nationalparkservice/npmap-symbol-library/issues/27#issuecomment-135799664

**Comment by jakecoolidge** [comment]
Here are the size variations based on the non-hitchhiker version:

<img src="https://cloud.githubusercontent.com/assets/11392872/9915780/2136ffda-5c76-11e5-9edf-a5f0b15c19d8.png" width="110" height="54" alt="statue-v1" >
