### ISSUE TITLE
Should this repo still be a fork of mapbox/maki?

### ISSUE THREAD

**Issue by williamscraigm** [nationalparkservice/symbol-library#29]
I understand that this repo borrows much from the mapbox/maki setup, but is there intention to ever merge?  Since github is restrictive with forks, it makes working with both mapbox/maki and this repo hard (forking this repo in the GitHub GUI just points to my mapbox/maki fork).

**Comment by nateirwin** [comment]
You make a good point, @williamscraigm.

We've veered away from Maki more and more, and have plans to completely sever the connection as we move to a new build system. I'll try to get to this soon.

**Comment by nateirwin** [comment]
Ok, I had GitHub support "unfork" this repository: https://github.com/nationalparkservice/npmap-symbol-library/network/members.
