### ISSUE TITLE
Adding color palette to NPMaki

### ISSUE THREAD

**Issue by makella** [nationalparkservice/symbol-library#4]
More than an issue, this is a thought I had... Should NPMaki encompass our color palette too? Our symbol set would include the icons and our color palette. Would love to hear any thoughts

**Comment by nateirwin** [comment]
This definitely works for me. I like the idea of having all of this encapsulated in a single project.

Does the base Maki project use/store colors?

**Comment by makella** [comment]
Not that I can see.

I am totally fine adding it here to the project (I realize the colors currently live in npmap.js which makes total sense)... 

I was thinking more along the lines of NPMaki our tool encapsulating our icons, colors, and any other symbology related things.  When we talk as a group about NPMaki, we are not only referring to the icon set but also to all other map symbol related items.  

@nateirwin I'll defer to you on the technical aspects of this idea, but that was the thought.

**Comment by jakecoolidge** [comment]
During our rebrand/rename NPMaki discussion, we came up with the idea to fold NPMap color palettes into Bootstrap. Should we open an issue over on that repo and close this one?

**Comment by nateirwin** [comment]
Yes, let's definitely do that!

**Comment by jakecoolidge** [comment]
This issue can now be found [over at Bootstrap.](https://github.com/nationalparkservice/bootstrap/issues/8)
