### ISSUE TITLE
Create webcam symbol

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#51]
Will support BLRI Live map development.

**Comment by jakecoolidge** [comment]
@mtaylorlong already completed this! Organizing issues to keep artwork linked to specific releases moving forward.

**Comment by mtaylorlong** [comment]
Thanks Jake!

**Comment by mtaylorlong** [comment]
Here's the initial symbol we're using: ![webcam-black-32](https://cloud.githubusercontent.com/assets/4741443/11756568/07b977a0-a018-11e5-85a5-fbb2891480a4.png)

**Comment by chadlawlis** [comment]
Is this called "webcam" in the symbol library? I'd like to link to it for the new "Webcam" preset.

**Comment by mtaylorlong** [comment]
Yes @cwlawlis802 – it will be called "webcam" in symbol library.

**Comment by chadlawlis** [comment]
:+1:
