### ISSUE TITLE
Add "emergency telephone"

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#55]
We have artwork for this symbol, but it hasn't been fully integrated into the library. It's the same symbol as the standard "telephone" symbol, but has a blue color applied to it (akin to the blue "H" for hospital).

_Not sure if this should be added, as-is, to Builder, since its color is problematic when placed over a colored placemarker._
- [ ] add to npmap-symbol-library.json file in the standalone symbol directory
- [ ] run render.sh to create updated png and sprite files.

**Comment by jakecoolidge** [comment]
There are currently three other symbols in the symbol library that have a color other than black, white, or gray applied to them. This is okay for standalone symbols, but problematic in Builder, where symbols are placed over a range of colors. Our approach has varied according to the symbol:
- Visitor Center: we maintained the green in this symbol by applying it to the "i" rather than the "building"
- Hospital: we simply made the "H" black or white; in hindsight this is perhaps sub-optimal, particularly as we have since made a complete set of capital letters for use in Builder.
- Waterfall: as with Hospital, we have black and white versions of this typically blue symbol. I'm interested in adopting HFC's waterfall symbol from their extended set, but that's a separate issue.

Back to Emergency Telephone: it is a preset in Places, and it would be good to have this fully integrated in the library. For use in Builder, I'm proposing a color-independent variant on the telephone:

| 12 | 18 | 24 |
| --- | --- | --- |
| ![emergency-telephone-12](https://cloud.githubusercontent.com/assets/11392872/12466530/80cbc5c8-bf92-11e5-8e7e-b97714aa2967.png) | ![emergency-telephone-11](https://cloud.githubusercontent.com/assets/11392872/12466531/80cd0d5c-bf92-11e5-9b9c-9e2f9a29ef46.png) | ![emergency-telephone-10](https://cloud.githubusercontent.com/assets/11392872/12466532/80cde614-bf92-11e5-9520-ad6f56859d6e.png) |

Let me know what you think.

**Comment by mtaylorlong** [comment]
I like it!    ...!

**Comment by jakecoolidge** [comment]
Just to cover all the bases, is it okay to support the symbols above in Builder, and continue with the blue phone symbols for standalone applications?

| 16 | 24 | 32 |
| --- | --- | --- |
| ![emergency-telephone-white-16](https://cloud.githubusercontent.com/assets/11392872/12466772/14cb7d12-bf94-11e5-878b-1d6e7289a967.png) | ![emergency-telephone-white-24](https://cloud.githubusercontent.com/assets/11392872/12466773/14cc8770-bf94-11e5-8630-3be0fdaef5cc.png) | ![emergency-telephone-white-32](https://cloud.githubusercontent.com/assets/11392872/12466771/14ca9c1c-bf94-11e5-9fcc-a1d984e39b74.png) |

**Comment by mtaylorlong** [comment]
It's definitely okay, although I'd lobby for making the standalone symbol the same. For the sake of getting these ready for the vector overlay though, the builder icon is all that matters in the immediate future.

**Comment by jakecoolidge** [comment]
okay, pushed these to the repo; we'll address the blue phone/exclamation point phone in a future release.
