### ISSUE TITLE
ATM

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#56]
For use with the "ATM" Places preset

**Comment by mtaylorlong** [comment]
Standalone atm symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![atm-black-32](https://cloud.githubusercontent.com/assets/4741443/12431421/96baa3b2-beb2-11e5-97e9-c928600cbf48.png) | ![atm-black-24](https://cloud.githubusercontent.com/assets/4741443/12431433/a1ecedf8-beb2-11e5-8c45-0abd2d69a5f0.png) | ![atm-black-16](https://cloud.githubusercontent.com/assets/4741443/12431436/a5b21cba-beb2-11e5-8eb6-c96be92bb976.png) |

**Comment by mtaylorlong** [comment]
HFC Symbol:
![screen shot 2016-01-19 at 1 47 51 pm](https://cloud.githubusercontent.com/assets/4741443/12431549/4b883a8e-beb3-11e5-83f0-092633669b96.png)
