### ISSUE TITLE
Bookstore

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#58]
For use with the "Bookstore" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbols
<img width="243" alt="screen shot 2016-01-20 at 10 08 36 am" src="https://cloud.githubusercontent.com/assets/4741443/12456608/d1a325a2-bf5d-11e5-8a12-a0bf5561e5e8.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![bookstore-black-32](https://cloud.githubusercontent.com/assets/4741443/12458934/71bbc318-bf69-11e5-9418-3dd5adad1a41.png) | ![bookstore-black-24](https://cloud.githubusercontent.com/assets/4741443/12458942/77458d5a-bf69-11e5-885a-e406f81d8368.png) | ![bookstore-black-16](https://cloud.githubusercontent.com/assets/4741443/12458952/7cf3d57c-bf69-11e5-969e-fcd13148a340.png) |
