### ISSUE TITLE
Dam

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#59]
For use with the "Dam" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
<img width="181" alt="screen shot 2016-01-21 at 11 10 33 am" src="https://cloud.githubusercontent.com/assets/4741443/12489844/a5e63cec-c02f-11e5-9ef8-24aca178b124.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![dam-black-32](https://cloud.githubusercontent.com/assets/4741443/12492155/32475de0-c03c-11e5-9685-cde598c204ba.png) | ![dam-black-24](https://cloud.githubusercontent.com/assets/4741443/12492159/35f678a4-c03c-11e5-9478-e505fcd1cd7e.png) | ![dam-black-16](https://cloud.githubusercontent.com/assets/4741443/12492160/37ebf4e0-c03c-11e5-8db5-c6f7e00e98ed.png) |
