### ISSUE TITLE
Add waterfall icon

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/symbol-library#6]
Add waterfall icon

**Comment by jakecoolidge** [comment]
I have an icon for this developed that I think is working pretty well. I'll leave the issue open until we add the icon to the larger set. We'll develop several and batch add them in a subsequent release of NPMaki in the next couple of months.

**Comment by makella** [comment]
Great! Did you decide if this is part of the basemap or overlay?  Depending on your decision how did that change the design of the icon?

**Comment by jakecoolidge** [comment]
My thinking is that the icon would be displayed, at large scales, in the basemap--provided we make the decision to support landmarks and natural features in the basemap. It is designed for Park Tiles Standard but also displays reasonably well on Slate.

**Comment by jakecoolidge** [comment]
Symbol added, [issue to update Builder](https://github.com/nationalparkservice/npmap-builder/issues/225) opened.
