### ISSUE TITLE
Lookout Tower

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#60]
For use with the "Tower" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbols:
![screen shot 2016-01-19 at 1 46 50 pm](https://cloud.githubusercontent.com/assets/4741443/12431524/2325c458-beb3-11e5-8b88-c10c94f8b75d.png)

**Comment by mtaylorlong** [comment]
I think we should name these consistently with hfc. So I'm going to name this `lookout-tower` in our symbol library.

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![lookout-tower-black-16](https://cloud.githubusercontent.com/assets/4741443/12456509/6fdc8d36-bf5d-11e5-8df7-ff3e2f060fff.png) | ![lookout-tower-black-24](https://cloud.githubusercontent.com/assets/4741443/12456520/7829bcd4-bf5d-11e5-91e0-5635f049c39c.png) | ![lookout-tower-black-32](https://cloud.githubusercontent.com/assets/4741443/12456525/7c944b4a-bf5d-11e5-9ff4-d2013b41a1c9.png) |
