### ISSUE TITLE
Mechanic (HFC "wrench" symbol)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#61]
For use with the "Garage" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
![screen shot 2016-01-20 at 12 57 26 pm](https://cloud.githubusercontent.com/assets/4741443/12461290/6460a93e-bf75-11e5-89d0-b7fc6499ac52.png)

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![mechanic-black-32](https://cloud.githubusercontent.com/assets/4741443/12465556/d482fb48-bf8b-11e5-943d-68a8a4ba9d78.png) | ![mechanic-black-24](https://cloud.githubusercontent.com/assets/4741443/12465559/d6b8378e-bf8b-11e5-8889-9bc5a366ab0d.png) | ![mechanic-black-16](https://cloud.githubusercontent.com/assets/4741443/12465563/d9bf9b02-bf8b-11e5-8646-3cd795e06755.png) |
