### ISSUE TITLE
Lighthouse

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#64]
For use with the "Lighthouse" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
<img width="366" alt="screen shot 2016-01-20 at 5 07 09 pm" src="https://cloud.githubusercontent.com/assets/4741443/12467405/4651cb80-bf98-11e5-815a-56c8727f9bc4.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![lighthouse-black-32](https://cloud.githubusercontent.com/assets/4741443/12489696/ca4833a2-c02e-11e5-9b68-94ff73083566.png) | ![lighthouse-black-24](https://cloud.githubusercontent.com/assets/4741443/12489698/cc3600e0-c02e-11e5-8802-e1e2a677dd13.png) | ![lighthouse-black-16](https://cloud.githubusercontent.com/assets/4741443/12489700/ce5606d6-c02e-11e5-9244-f073905f0050.png) |
