### ISSUE TITLE
Museum

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#65]
For use with the "Museum" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbols
<img width="321" alt="screen shot 2016-01-20 at 3 43 48 pm" src="https://cloud.githubusercontent.com/assets/4741443/12465701/a21ccb74-bf8c-11e5-878f-76c83933af5f.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![museum-black-32](https://cloud.githubusercontent.com/assets/4741443/12467353/e738ecf0-bf97-11e5-802a-7599d51d39cf.png) | ![museum-black-24](https://cloud.githubusercontent.com/assets/4741443/12467363/ef54e826-bf97-11e5-8831-f58a066a9444.png) | ![museum-black-16](https://cloud.githubusercontent.com/assets/4741443/12467364/f2402adc-bf97-11e5-8b86-9fc211b983db.png) |
