### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#66]
For use with the "Playground" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
<img width="251" alt="screen shot 2016-01-21 at 12 42 15 pm" src="https://cloud.githubusercontent.com/assets/4741443/12493744/bec46fd6-c043-11e5-8140-0184955ff039.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![playground-black-32](https://cloud.githubusercontent.com/assets/4741443/12495573/ade53fa6-c04d-11e5-8c2c-44f4db440231.png) | ![playground-black-24](https://cloud.githubusercontent.com/assets/4741443/12495577/aff32c18-c04d-11e5-82a8-a0d8b5ca8c9a.png) | ![playground-black-16](https://cloud.githubusercontent.com/assets/4741443/12495580/b1bda3c0-c04d-11e5-88ba-ae5392aa6e89.png) |
