### ISSUE TITLE
Sea Plane

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#67]
For use with the "Seaplane Base" Places preset

**Comment by jakecoolidge** [comment]
I'm finding HFC's sea plane artwork starts to break down a bit at smaller sizes. In the variant below, I have the plane taking off from the waves&mdash;does this aid the legibility of the symbol in any way? (All images are at 72ppi resolution.) @nateirwin @cwlawlis802 @mtaylorlong @jimmyrocks 

|  | 16px | 24px | 32px |
| --- | --- | --- | --- |
| original | ![sea-plane_black-16](https://cloud.githubusercontent.com/assets/11392872/12434607/034c0126-bec5-11e5-9489-f619eafbb2b5.png) | ![sea-plane_black-24](https://cloud.githubusercontent.com/assets/11392872/12434605/03471d3c-bec5-11e5-9948-501ac9797d69.png) | ![sea-plane_black-32](https://cloud.githubusercontent.com/assets/11392872/12434610/0353974c-bec5-11e5-9a5f-49526ba4735a.png) |
| variant | ![sea-plane_black-16-variant](https://cloud.githubusercontent.com/assets/11392872/12434609/035317fe-bec5-11e5-851c-55831b369649.png) | ![sea-plane_black-24-variant](https://cloud.githubusercontent.com/assets/11392872/12434606/0349cb40-bec5-11e5-93b5-c258013c0d94.png) | ![sea-plane-black-32-variant](https://cloud.githubusercontent.com/assets/11392872/12434608/0351799e-bec5-11e5-9f38-eafa83972981.png) |

**Comment by mtaylorlong** [comment]
I like it! Much more active. I think you should go for it in this round. We can always solicit HFC feedback and make modifications on our next pass. It's a pretty obscure symbols, so I'm sure a few changes over time wouldn't disrupt much.

**Comment by jakecoolidge** [comment]
Nice! When the artwork elements are so small, getting some separation between them might help. And I agree, we can always change symbols, even after we release them into the wild.

**Comment by jakecoolidge** [comment]
Completed variants with the "take-off" version. Closing for now, but feedback is welcome.
