### ISSUE TITLE
Souvenir Shop

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#69]
For use with the "Gift Shop" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol:
<img width="283" alt="screen shot 2016-01-20 at 11 33 48 am" src="https://cloud.githubusercontent.com/assets/4741443/12458995/b4b61114-bf69-11e5-8b0f-e1bf6bbc0c58.png">

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![souvenir-black-32](https://cloud.githubusercontent.com/assets/4741443/12461087/50bf4882-bf74-11e5-9579-e1a0b4b53b40.png) | ![souvenir-black-24](https://cloud.githubusercontent.com/assets/4741443/12461088/50c3e360-bf74-11e5-8b3a-50d01abf708d.png) | ![souvenir-black-16](https://cloud.githubusercontent.com/assets/4741443/12461086/50be4e6e-bf74-11e5-9c7c-14312b25623a.png) |
