### ISSUE TITLE
Add RV Dumpstation Icon

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/symbol-library#7]
Add RV Dumpstation Icon

**Comment by makella** [comment]
@tpcolson this will be there in our new update which should be coming soon... I'll let you know when it is out there.

**Comment by jakecoolidge** [comment]
@tpcolson is this the symbol you're referring to?
https://github.com/nationalparkservice/npmap-symbol-library/blob/gh-pages/svg-set-comprehensive/sanitary-disposal-station-black-32.svg

**Comment by jakecoolidge** [comment]
Closing this; pretty sure Tom was looking for the sanitary disposal station symbol back in April.
