### ISSUE TITLE
Cave

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#70]
For use with the "Cave Entrance" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
<img width="320" alt="screen shot 2016-01-22 at 9 23 24 am" src="https://cloud.githubusercontent.com/assets/4741443/12518933/daa2b25c-c0f8-11e5-9f03-d90be9087f91.png">

In the context of places POI's this will apply mainly to caves (and any other cave-related item, but currently there are none). As such, I'm going to simply name this `cave` in our symbol library.

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![cave-black-32](https://cloud.githubusercontent.com/assets/4741443/12518968/0f526fb0-c0f9-11e5-90a4-612d12e03656.png) | ![cave-black-24](https://cloud.githubusercontent.com/assets/4741443/12518971/10ffa594-c0f9-11e5-9263-2b5c9ae8bc42.png) | ![cave-black-16](https://cloud.githubusercontent.com/assets/4741443/12518973/12766098-c0f9-11e5-8348-15a66f2ea019.png) |
