### ISSUE TITLE
Theater

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#71]
For use with the "Cinema" Places preset

**Comment by mtaylorlong** [comment]
HFC Symbol
<img width="212" alt="screen shot 2016-01-22 at 8 08 28 am" src="https://cloud.githubusercontent.com/assets/4741443/12516143/204f771e-c0e9-11e5-8898-5281beec4f4e.png">

This one will need a bit of tweaking to retain the detail of seats vs. people. In smaller version, I'll probably have to abandon the seats altogether.

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![theater-black-32](https://cloud.githubusercontent.com/assets/4741443/12516163/45fdfd46-c0e9-11e5-805b-6e2be4cc8444.png) | ![theater-black-24](https://cloud.githubusercontent.com/assets/4741443/12516165/476d5e1a-c0e9-11e5-8f68-4a162c638e2b.png) | ![theater-black-16](https://cloud.githubusercontent.com/assets/4741443/12516166/4915ba82-c0e9-11e5-807a-c83cc0e1738c.png) |

This one was tough. cc: @jakecoolidge
