### ISSUE TITLE
Sign

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/symbol-library#76]
For use with potentially several Places presets in superclass=information; class=sign:
- Directional Sign
- Gateway Sign
- Mile Marker
- Regulatory Sign
- Trail Marker
- Trail Sign

**Comment by mtaylorlong** [comment]
There no existing HFC symbol for a generic sign, but it would be a very useful catch-all for us to use with POI's. Here's my idea:
![sign-black-32-draft1](https://cloud.githubusercontent.com/assets/4741443/12496061/966a08b8-c050-11e5-978c-acc27f30b9ce.png)
@jakecoolidge: What do you think of this?

**Comment by jakecoolidge** [comment]
Looks good to me! You'll probably have to modify or remove the linework inside the sign at smaller sizes, but I like the direction.

**Comment by mtaylorlong** [comment]
After more discussion, we've settled on a simpler design that's more NPS-ish:
![sign-black-32-draft4](https://cloud.githubusercontent.com/assets/4741443/12497253/e210188c-c057-11e5-81f7-0ae89aec1567.png)

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![sign-black-32](https://cloud.githubusercontent.com/assets/4741443/12497687/95799324-c05a-11e5-8ce6-ebbbf496ba5e.png) | ![sign-black-24](https://cloud.githubusercontent.com/assets/4741443/12497690/977a54ec-c05a-11e5-8d6e-98c0ebd50e98.png) | ![sign-black-16](https://cloud.githubusercontent.com/assets/4741443/12497692/993b07ea-c05a-11e5-9a1f-e4df6fc54713.png) |
