### ISSUE TITLE
Create icons for Places Mobile

### ISSUE THREAD

**Issue by makella** [nationalparkservice/symbol-library#9]
It would be great to get NPMaki 1.0 styled icons for the following icons used in Places Mobile (there may be more in the future). The 12,18,24 sizes will be good.
- flagpole
- building entrance
- railroad crossing 
- statue (generic)

I can provide the files that I've used to create the initial versions of these (outside of the NPMaki framework)

**Comment by jakecoolidge** [comment]
If you think the following are in good shape, you can check them off the list:
- [ ] [flagpole](https://github.com/nationalparkservice/npmap-symbol-library/issues/24)
- [ ] [building entrance](https://github.com/nationalparkservice/npmap-symbol-library/issues/25)
- [ ] [railroad crossing](https://github.com/nationalparkservice/npmap-symbol-library/issues/26)
- [ ] [statue (generic)](https://github.com/nationalparkservice/npmap-symbol-library/issues/27)

I started, but did not complete, a statue symbol. Let me know if you'd like me to return to this.

Once all are checked off, I'll close the issue.

**Comment by jakecoolidge** [comment]
I'm going to track these symbols by creating a separate issue for each.
