### ISSUE TITLE
Dot (for POI's with no available symbol)

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/symbol-library#92]
I'm taking the liberty of adding one more symbol to our to-do list for the 2.2.0 release: Dot. The dot symbol is needed for POI types that don't have a corresponding symbol in our library.

@nateirwin said he could render the dot in the browser, which is probably the best plan, but I though it would be nice to have one in the library ready to go as a back-up. It won't take long.

**Comment by nateirwin** [comment]
I like it... "Dot". Really rolls off the tongue.

**Comment by mtaylorlong** [comment]
Hah. I thought it would be better than "point" since there's "viewpoint", "point of interest", etc.

**Comment by mtaylorlong** [comment]
@nateirwin: I'm open to other name suggestions though...

**Comment by mtaylorlong** [comment]
Standalone symbol designs:

| 32 | 24 | 16 |
| --- | --- | --- |
| ![dot-black-32](https://cloud.githubusercontent.com/assets/4741443/12498248/5d9ba6c8-c05e-11e5-80ea-3d5b37b2d8ac.png) | ![dot-black-24](https://cloud.githubusercontent.com/assets/4741443/12498251/5f866608-c05e-11e5-91e4-0b4c738d9bda.png) | ![dot-black-16](https://cloud.githubusercontent.com/assets/4741443/12498253/6128c320-c05e-11e5-9fed-fc4dbf6ef4ec.png) |
